title: Workflows University
description: World of Workflows Information
theme: just-the-docs

url: https://world-of-workflows.github.io/WorkflowsUniversity/

aux_links:
  Template Repository: https://github.com/world-of-workflows/WorkflowsUniversity